<?php
$is_validated=Mage::getStoreConfig('socialloginsc_options/apisettings/scsl_validated');

$file_headers = get_headers("https://www.socleversocial.com/dashboard/scon.php");
if(strpos($file_headers[0], '200') !== false)
{
  $soclever_on=1;
  
} 
else
{
    $is_validated=1;
    $soclever_on=0;
}

if($is_validated=='1' && $soclever_on==1)
{
$CsorderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
$Csorder = Mage::getModel('sales/order')->loadByIncrementId($CsorderId);

$sessionVariable = Mage::getSingleton('core/session')->getSessionVariable();

echo"<img src='https://www.socleversocial.com/dashboard/trackPixel.php?site_id=".Mage::getStoreConfig('socialloginsc_options/apisettings/scsl_siteid')."&order_id=".$CsorderId."&ord_amt=".$Csorder->getGrandTotal()."&ord_cur=".$Csorder->base_currency_code."&siteUid=".$Csorder->customer_id."&is_from=".$sessionVariable."' />";

}
?>