<?php
$site_id=Mage::getStoreConfig('sociallogin_options/apisettings/scsl_siteid');
$api_secret=Mage::getStoreConfig('sociallogin_options/apisettings/scsl_appsecret');
$api_key=Mage::getStoreConfig('sociallogin_options/apisettings/scsl_appid');  
$btn_style=Mage::getStoreConfig('sociallogin_options/displaysettings/buttonstyle');
$button_size=Mage::getStoreConfig('sociallogin_options/displaysettings/buttonsize');
          
          $valid_data=file_get_contents("https://www.socleversocial.com/dashboard/mage_activate.php?site_id=".$site_id."&api_key=".$api_key."&api_secret=".$api_secret."&csplatform=magentologin&rt=gp&bstyle=".$btn_style."&bsize=".$button_size);
          
          if($valid_data && $valid_data!='0~~0')
          {
            echo $valid_data;
          }
         else
         {
           echo"<h1>Please provide valid API setting</h1>";
         }
 
 
            
        
        
        
    


?>