<?php
$CsorderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
$Csorder = Mage::getModel('sales/order')->loadByIncrementId($CsorderId);

 

$sessionVariable = Mage::getSingleton('core/session')->getSessionVariable();


//echo "https://www.socleversocial.com/dashboard/trackPixel.php?site_id=".Mage::getStoreConfig('sociallogin_options/apisettings/scsl_siteid')."&order_id=".$CsorderId."&ord_amt=".$Csorder->subtotal_incl_tax."&ord_cur=".$Csorder->base_currency_code."&siteUid=".$Csorder->customer_id;

echo"<img src='https://www.socleversocial.com/dashboard/trackPixel.php?site_id=".Mage::getStoreConfig('sociallogin_options/apisettings/scsl_siteid')."&order_id=".$CsorderId."&ord_amt=".$Csorder->getGrandTotal()."&ord_cur=".$Csorder->base_currency_code."&siteUid=".$Csorder->customer_id."&is_from=".$sessionVariable."' />";
//print_r($Csorder);

?>